languageCode = "cn-CN"
languageName = "中文"
weight = 2
title = "晚星"
contentDir = 'content/pt'


[params]
  displayName = "CN"
  isoCode = "cn-CN"
  rtl = false
  # logo = "img/logo.png"
  description = "O meu website awesome"
  # copyright = "Copy, _right?_ :thinking_face:"

dateFormat = "2 January 2006"

[params.author]
  name = "Vincent Lu"
  image = "img/avatar.png"
  headline = "更晚的星星会照亮更广阔的夜空。"
  bio = "A little bit about you"
   links = [
     { link = "https://nunocoracao.github.io/blowfish/" },
     { github = "https://github.com/nunocoracao/blowfish" },
     { x-twitter = "https://twitter.com/burufugu" }
   ]
