languageCode = "en"
languageName = "English"
weight = 1
title = "Late Star"
contentDir = 'content/en'


[params]
  displayName = "EN"
  isoCode = "en"
  rtl = false
  # logo = "img/logo.png"
  description = "My awesome website"
  # copyright = "Copy, _right?_ :thinking_face:"
  dateFormat = "2 January 2006"

[params.author]
  name = "Vincent Lu"
  image = "img/avatar.png"
  headline = "Shine later, but brighter."
  bio = "What do you think?"
   links = [
     { github = "https://github.com/vincentluting/vincentluting.github.io" },
     { linkedin = "https://www.linkedin.com/in/ting-lu-vincent/" },
   ]
