languageCode = "zh-cn"
languageName = "简体中文"
weight = 2
title = "晚星"
contentDir = 'content/cn'


[params]
  displayName = "简体中文"
  isoCode = "zh-cn"
  rtl = false
  logo = "img/logo.png"
  description = "O meu website awesome"
  # copyright = "Copy, _right?_ :thinking_face:"

dateFormat = "2 January 2006"

[params.author]
  name = "Vincent Lu"
  image = "img/avatar.png"
  headline = "迟迟闪耀，愈晚愈明。"
  bio = "在滚滚科技浪潮中觅得一隅安放灵魂的岛屿。"
   links = [
     { github = "https://github.com/vincentluting/vincentluting.github.io" },
     { linkedin = "https://www.linkedin.com/in/ting-lu-vincent/" },
   ]
