languageCode = "en"
languageName = "English"
weight = 1
title = "Gray Blowfish"
contentDir = 'content/en'


[params]
  displayName = "EN"
  isoCode = "en"
  rtl = false
  # logo = "img/logo.png"
  description = "My awesome website"
  # copyright = "Copy, _right?_ :thinking_face:"
  dateFormat = "2 January 2006"

[params.author]
  name = "Gray Blowfish"
  image = "img/avatar.png"
  headline = "This is my very simple profile website with my links"
  bio = "A little bit about you"
   links = [
     { github = "https://github.com/vincentluting/vincentluting.github.io" },
   ]
